### ISSUE TITLE
Should we setup a directory structure?

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/movingfeatures#1]
Should we organize the content in subdirectories for making easier to identifies purpose of files? A possible organization could be:

```
README.md
images/
  ├─ access.png
  ├─ applications.png
  ├─ modularity.png
  └─ tracks.png
data/
  └─ csv/
     └─ mf.csv
code/
  └─ jupyter/
     ├─ Load+OGC+Moving+Features+CSV.ipynb
     └─ LoadOGCMovingFeaturesCSV.html
```

Of course this is only a proposal, other directory layout proposal are welcome!

Also, should we rename `mf.csv` as `walkers.csv` since we may have other "moving features" files to add?

**Comment by akinori-asahara** [comment]
Sorry for very very very late reaction.
The structure was revised.

**Comment by desruisseaux** [comment]
Thanks! I think we can close this issue then.
